language: node_js
node_js:
  - node
sudo: false
before_install:
  - npm install -g yarn@^0.16.0
install:
  - yarn
script:
  - yarn lint
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
